---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperlessai-ingress
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - paperlessai.dassidias.com
    secretName: paperlessai-tls
  rules:
  - host: paperlessai.dassidias.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paperlessai-service
            port:
              number: 80