

# Deployment for the nextcloud application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate  # Ensures only one version runs at a time
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Edmonton  # Set timezone for the container
          image: lscr.io/linuxserver/nextcloud:latest  # Main app image
          name: nextcloud
          ports:
            - containerPort: 443  # Expose port 443 inside the container
              protocol: TCP
          volumeMounts:
            - mountPath: /data  
              name: nextcloud-claim-data
            - mountPath: /config      
              name: homepage-app-config-volume
      restartPolicy: Always
      volumes:
        - name: homepage-app-config-data
          nfs:
            server: 192.168.1.52
            path: /mnt/Home/storage
            readOnly: false
        - name: homepage-app-config-volume
          nfs:
            server: 192.168.1.52
            path: /mnt/Home/App_Config/homepage
            readOnly: false


