
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dozzle-ingress
  labels:
    app: dozzle
  namespace: dozzle
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Use cert-manager for TLS
    nginx.ingress.kubernetes.io/rewrite-target: /        # Rewrite all paths to root
    nginx.ingress.kubernetes.io/proxy-body-size: "0"    # Increase max upload size
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - logs.dassidias.com
    secretName: dozzle-tls  # Secret where TLS cert will be stored
  rules:
  - host: logs.dassidias.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dozzle-service  # Route to this service
            port:
              number: 80                 # Service port to route to
---