apiVersion: v1
kind: Service
metadata:
  labels:
    app: dozzle
  name: dozzle-service
  namespace: dozzle
spec:
  ports:
    - name: "8080"
      port: 80
      targetPort: 8080
  selector:
    app: dozzle
